config/routes.rb
Rails.application.routes.draw do
  get '/' => 'root#top'

  get 'posts' => 'posts#index'
  post 'posts/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch 'posts/:id' => 'posts#update', as: 'update_post'
  delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'
  get 'posts/:id' => 'posts#show', as: 'post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
  	@post = Post.new
  end

  def create
  	post = Post.new(post_params)
  	post.save
    flash[:notice] = "Successfully Completed!!"
  	redirect_to post_path(post.id)
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    flash[:notice] = "Successfully Completed!!"
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "Successfully Completed!!"
    redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
	<label for="post_title"> Title</label>
	<span><%= f.text_field :title, class:"book_title" %></span>
	<label for="post_body"> Body</label>
	<span><%= f.text_area :body, class:"book_body" %></span>
	<span><%= f.submit 'Update Book' %></span>
<% end %>

<%= link_to "Show", post_path(@post.id), class:"show_#{@post.id}" %>
|
<%= link_to "Back", posts_path, class:"back" %>

app/views/posts/index.html.erb
<h1>Books</h1>

<table>
	<tr>
		<th>Title</th><th>Body</th><th colspan="3"></th>
	</tr>
		<% @posts.each do |post| %>
	<tr>
		<td><%= post.title %></td>
		<td><%= post.body %></td>
		<td><%= link_to "Show", post_path(post.id), class:"show_#{post.id}" %></td>
		<td><%= link_to "Edit", edit_post_path(post.id), class:"edit_#{post.id}" %></td>
		<td><%= link_to "Destroy", destroy_post_path(post.id), class:"destroy_#{post.id}", method: :delete, "data-confirm" => "Are you sure?" %></td>
	</tr>
		<% end %>
</table>

<h2>New book</h2>

<%= form_for @post, url: posts_create_path do |f| %>

	<label for="post_title"> Title</label>
	<span><%= f.text_field :title, class:"book_title" %></span>

	<label for="post_body"> Body</label>
	<span><%= f.text_area :body, class:"book_body" %></span>
	<span><%= f.submit 'Create Book' %></span>
<% end %>

app/views/posts/show.html.erb
<p>
	<strong>Title:</strong> <%= @post.title %>
</p>
<p>
	<strong>Body:</strong> <%= @post.body %>
</p>

<%= link_to "Edit", edit_post_path(@post.id), class:"edit_#{@post.id}" %>
|
<%= link_to "Back", posts_path, class:"back" %>

app/views/root/top.html.erb
<h1>
	ようこそ<strong>Bookers</strong>へ！
</h1>

<p>
<strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to("start","/posts") %></p>